from enum import Enum
from city import City  # Adjust the import based on your project structure

EPIDEMIC = "Epidemic"

class PlayerDeck(Enum):
    ALGIERS = City.ALGIERS
    ATLANTA = City.ATLANTA
    BAGHDAD = City.BAGHDAD
    BANGKOK = City.BANGKOK
    BEIJING = City.BEIJING
    BOGOTA = City.BOGOTA
    BUENOS_AIRES = City.BUENOS_AIRES
    CAIRO = City.CAIRO
    CHENNAI = City.CHENNAI
    CHICAGO = City.CHICAGO
    DELHI = City.DELHI
    ESSEN = City.ESSEN
    HO_CHI_MINH_CITY = City.HO_CHI_MINH_CITY
    HONG_KONG = City.HONG_KONG
    ISTANBUL = City.ISTANBUL
    JAKARTA = City.JAKARTA
    JOHANNESBURG = City.JOHANNESBURG
    KARACHI = City.KARACHI
    KHARTOUM = City.KHARTOUM
    KINSHASA = City.KINSHASA
    KOLKATA = City.KOLKATA
    LAGOS = City.LAGOS
    LIMA = City.LIMA
    LONDON = City.LONDON
    LOS_ANGELES = City.LOS_ANGELES
    MADRID = City.MADRID
    MANILA = City.MANILA
    MELBOURNE = City.MELBOURNE
    MEXICO_CITY = City.MEXICO_CITY
    MIAMI = City.MIAMI
    MILAN = City.MILAN
    MONTREAL = City.MONTREAL
    MOSCOW = City.MOSCOW
    MUMBAI = City.MUMBAI
    NEW_YORK = City.NEW_YORK
    OSAKA = City.OSAKA
    PARIS = City.PARIS
    RIYADH = City.RIYADH
    SAN_FRANCISCO = City.SAN_FRANCISCO
    SANTIAGO = City.SANTIAGO
    SAO_PAULO = City.SAO_PAULO
    SEOUL = City.SEOUL
    SHANGHAI = City.SHANGHAI
    ST_PETERSBURG = City.ST_PETERSBURG
    SYDNEY = City.SYDNEY
    TAIPEI = City.TAIPEI
    TOKYO = City.TOKYO
    WASHINGTON = City.WASHINGTON
    EPIDEMIC = EPIDEMIC
